version: '3.7'

services:
  analyze_bff:
    build: ../analyze-that-bff
    volumes:
      - ../analyze-that-bff/:/app/
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ../analyze-that-bff/.env
    ports:
      - 8000:8000

  analyze_web:
    build: ../analyze-that-ui-web
    volumes:
      - ../analyze-that-ui-web/:/app/
    ports:
      - 8080:80

  analyze_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_bff:/var/lib/postgresql/data/
    env_file:
      - ../analyze-that-bff/.env
    ports:
      - 5432:5432

volumes:
  postgres_data_bff: