version: '3.7'

services:
  analyze_bff:
    container_name: analyze-that-bff
    build: ../analyze-that-bff
    restart: always
    volumes:
      - ../analyze-that-bff/:/app/
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ../analyze-that-bff/.env
    ports:
      - 8000:8000

  analyze_web:
    container_name: analyze-that-web
    build: ../analyze-that-ui-web
    restart: always
    volumes:
      - ../analyze-that-ui-web/:/app/
    ports:
      - 8080:80

  analyze_db:
    container_name: analyze-that-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data_bff:/var/lib/postgresql/data/
    env_file:
      - ../analyze-that-bff/.env
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: analyze@that.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - 8088:80

volumes:
  postgres_data_bff: